var data = [
    null,
    [
        "",
        [
            [1357037952, "填寫者姓名", null, 0, [[1856443187, null, 1]]],
            [
                1605712897,
                "班級",
                null,
                3,
                [
                    [
                        762925573,
                        [
                            ["301", null, null, null, 0],
                            ["302", null, null, null, 0],
                            ["303", null, null, null, 0],
                            ["304", null, null, null, 0],
                            ["305", null, null, null, 0],
                            ["306", null, null, null, 0],
                            ["307", null, null, null, 0],
                            ["308", null, null, null, 0],
                            ["309", null, null, null, 0],
                            ["310", null, null, null, 0],
                            ["311", null, null, null, 0],
                            ["312", null, null, null, 0],
                            ["313", null, null, null, 0],
                            ["314", null, null, null, 0],
                            ["315", null, null, null, 0],
                            ["316", null, null, null, 0],
                            ["317", null, null, null, 0],
                            ["318", null, null, null, 0],
                            ["319", null, null, null, 0],
                            ["320", null, null, null, 0],
                            ["321", null, null, null, 0],
                            ["322", null, null, null, 0],
                            ["323", null, null, null, 0],
                            ["324", null, null, null, 0],
                            ["325", null, null, null, 0],
                            ["326", null, null, null, 0],
                            ["327", null, null, null, 0],
                            ["328", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                24572961,
                "1.上課日期",
                null,
                9,
                [[917412650, null, 1, null, null, null, null, [0, 1]]],
            ],
            [
                986663738,
                "2.第一節",
                null,
                3,
                [
                    [
                        14235153,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                829485021,
                "3.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[329893755, null, 1]],
            ],
            [
                2127098016,
                "4.教師出席狀況",
                null,
                2,
                [
                    [
                        1556327835,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於4-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於4-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與4-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1938885379,
                "4-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[119822768, null, 0]],
            ],
            [
                360302987,
                "5.第二節",
                null,
                3,
                [
                    [
                        634850437,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                609733592,
                "6.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[714947543, null, 1]],
            ],
            [
                840872135,
                "7.教師出席狀況",
                null,
                2,
                [
                    [
                        869445378,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於7-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於7-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與7-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1941868436,
                "7-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[1786512999, null, 0]],
            ],
            [
                1044978206,
                "8.第三節",
                null,
                3,
                [
                    [
                        403989627,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                2062693589,
                "9.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[604197935, null, 1]],
            ],
            [
                686714720,
                "10.教師出席狀況",
                null,
                2,
                [
                    [
                        635206839,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於10-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於10-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與10-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1949153266,
                "10-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[17245382, null, 0]],
            ],
            [
                2093674265,
                "11.第四節",
                null,
                3,
                [
                    [
                        909035250,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                750400321,
                "12.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[398244057, null, 1]],
            ],
            [
                923196471,
                "13.教師出席狀況",
                null,
                2,
                [
                    [
                        2007587202,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於13-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於13-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與13-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                291518000,
                "13-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[904910944, null, 0]],
            ],
            [
                1160010877,
                "14.第五節",
                null,
                3,
                [
                    [
                        574229561,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                801075953,
                "15.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[1113381671, null, 1]],
            ],
            [
                608575934,
                "16.教師出席狀況",
                null,
                2,
                [
                    [
                        72674477,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於16-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於16-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與16-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1812740227,
                "16-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[405077547, null, 0]],
            ],
            [
                1032913993,
                "17.第六節",
                null,
                3,
                [
                    [
                        1739516506,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                790049442,
                "18.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[871461081, null, 1]],
            ],
            [
                756649130,
                "19.教師出席狀況",
                null,
                2,
                [
                    [
                        1308935777,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於19-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於19-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與19-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                290347248,
                "19-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[1174172028, null, 0]],
            ],
            [
                1009480341,
                "20.第七節",
                null,
                3,
                [
                    [
                        2061162996,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1287140018,
                "21.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[1732679242, null, 1]],
            ],
            [
                1238097733,
                "22.教師出席狀況",
                null,
                2,
                [
                    [
                        1552416909,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於22-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於22-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與22-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                2266271,
                "22-1本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[257855159, null, 0]],
            ],
            [
                196678485,
                "23.第八節",
                null,
                3,
                [
                    [
                        1235594214,
                        [
                            ["無第八節", null, null, null, 0],
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1958263994,
                "24.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可；若無第八節的班級，填「無第八節」即可）",
                null,
                0,
                [[571339789, null, 1]],
            ],
            [
                959195205,
                "25.教師出席狀況",
                null,
                2,
                [
                    [
                        85147417,
                        [
                            ["無第八節", null, null, null, 0],
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於25-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於25-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與25-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                640017267,
                "25-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[1296767361, null, 0]],
            ],
        ],
        ["", 1, 0, 1, 0],
        null,
        null,
        [1, 1],
        null,
        [1, ""],
        "110-1高三課程教室日誌        ",
        51,
        [null, null, null, 2, 0],
        null,
        null,
        null,
        null,
        [2],
        [[1, 1, 1, 1, 1], 1],
    ],
    "/forms",
    "110-1高三課程教室日誌        ",
    null,
    null,
    null,
    "1",
    null,
    0,
    1,
    null,
    "臺北市立建國高級中學",
    1,
    "e/1FAIpQLSdXlbwviHhDTCnzXxBWlN73SAEU7HaFVlvStOU0FaxUkCymUg",
    0,
    '[{"data":{"value":[]},"keyPath":["syncMap","applicationFonts","6"],"state":{"hashValue":"00000000"}},{"data":{"value":[]},"keyPath":["syncMap","domainFonts","0"],"state":{"hashValue":"00000000"}},{"data":{"familyList":["Alegreya","Amatic SC","Bree Serif","Calibri","Cambria","Merriweather","Permanent Marker","Pinyon Script","Playfair Display","Proxima Nova","Roboto","Roboto Mono","Ultra","Varela Round"],"recentlyUsedFamilyList":["LiHei Pro","Courier New","BiauKai","Arial","Times New Roman"],"transitionedFamilyList":[],"hasTransitioned":true},"keyPath":["syncMap","preferences","docs-fonts"],"state":{"timestamp":1622034479085335}},{"data":{"editorAnalyticsOnboarding":true,"blameLaunch":true,"saveIndicator":true,"smartCompose":true,"meetInEditorsPromo":true},"keyPath":["syncMap","preferences","docs-global_promos","0"],"state":{"timestamp":1628155928800995}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-unsupported_feature_warning_callout_bubble_shown_count"],"state":{"timestamp":1632229045539000}},{"data":{"value":false},"keyPath":["syncMap","preferences","mae-show_addons_menu_promo"],"state":{"timestamp":1632229045541000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-aips"],"state":{"timestamp":1632229045542000}},{"data":{},"keyPath":["syncMap","preferences","docs-homescreen-asp","6"],"state":{"timestamp":1628155928800995}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-homescreen-ftbdct"],"state":{"timestamp":1632229045542000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-dbs"],"state":{"timestamp":1632229045542000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-ht"],"state":{"timestamp":1632229045542000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-wws"],"state":{"timestamp":1632229045542000}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-etg-lvt"],"state":{"timestamp":1632229045544000}},{"data":{"value":true},"keyPath":["syncMap","preferences","docs-screenreader"],"state":{"timestamp":1629435255205059}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-enable_braille"],"state":{"timestamp":1629435255205059}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-mute_collaborators"],"state":{"timestamp":1629435255205059}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_chooser"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_link_form_promo"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_whats_new"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-expand_dasher_options"],"state":{"timestamp":1631668543776424}},{"data":{"proto":"[]"},"keyPath":["syncMap","preferences","freebird-auto_create_sink"],"state":{"timestamp":1632229045549000}},{"data":{"proto":"[]"},"keyPath":["syncMap","preferences","freebird-ui_version"],"state":{"timestamp":1632229045551000}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-questions_required_by_default"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-collect_usernames_by_default"],"state":{"timestamp":1631668543776424}},{"data":{"value":0},"keyPath":["syncMap","preferences","freebird-default_point_value"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_assessments_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-autovalidate_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_qxq_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_braveheart_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_manual_grading_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_record_view_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_brain_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-has_seen_braveheart_theme_warning"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_custom_themes_toast"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_edu_bundle_18_toast"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_quizzes_intro"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_question_import_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_locked_mode_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_draft_responses_modal"],"state":{"timestamp":1631668543776424}}]',
    1,
    0,
]

const subset = data[1][1]
var entrycode = []
const viewUrl =
    "https://docs.google.com/forms/d/e/1FAIpQLSdXlbwviHhDTCnzXxBWlN73SAEU7HaFVlvStOU0FaxUkCymUg/viewform?"
const submitUrl =
    "https://docs.google.com/forms/d/e/1FAIpQLSdXlbwviHhDTCnzXxBWlN73SAEU7HaFVlvStOU0FaxUkCymUg/formResponse?"

subset.forEach((item) => {
    const entry = item[4][0][0]
    const title = item[1]
    entrycode.push(`entry.${entry}={${title}}`)
})

function update() {
    const date = document.getElementsByName("date")[0]
    const dt = new Date(date.value)
    const classes = [
        null,
        [
            "化學",
            "彈性學習－化學",
            "跨班加深加廣",
            "跨班加深加廣",
            "彈性學習－生物",
            "國文",
            "國文",
        ],
        ["化學", "化學", "英文", "英文", "美術", "美術", "全民國防教育"],
        [
            "數學",
            "數學",
            "跨班加深加廣",
            "跨班加深加廣",
            "綜合活動",
            "跨班加深加廣",
            "跨班加深加廣",
        ],
        [
            "數學",
            "彈性學習－數學",
            "健康與護理",
            "健康與護理",
            "英文",
            "英文",
            "體育",
        ],
        ["國文", "國文", "數學", "班會", "體育", "生物", "生物"],
        null,
    ]
    const currentDay = classes[dt.getDay()]

    const list = ["1", "2", "3", "4", "5", "6", "7"]

    list.forEach((item) => {
        const p = document.getElementById(item)
        p.innerHTML = currentDay[parseInt(item) - 1]
    })
}

function processFormData() {
    const classnames = [
        document.getElementById("1").innerHTML,
        document.getElementById("2").innerHTML,
        document.getElementById("3").innerHTML,
        document.getElementById("4").innerHTML,
        document.getElementById("5").innerHTML,
        document.getElementById("6").innerHTML,
        document.getElementById("7").innerHTML,
    ]
    console.log(classnames)
    const teachers = {
        國文: "王曼莉",
        英文: "柳雅馨",
        數學: "黃智昇",
        綜合活動: "無",
        班會: "黃智昇",
        "彈性學習－數學": "黃智昇",
        化學: "曹淇峰",
        "彈性學習－化學": "曹淇峰",
        生物: "劉翠華",
        "彈性學習－生物": "劉翠華",
        跨班加深加廣: "無",
        美術: "趙依誠",
        全民國防教育: "戴慎孜",
        健康與護理: "戴芳台",
        體育: "蔡家豪",
    }
    const date = document.getElementsByName("date")[0].value
    const entrydata = [
        "entry.1856443187=黃靖緯",
        "entry.762925573=313",
        `entry.917412650=${date}`,
        `entry.14235153=${classnames[0]}`,
        `entry.329893755=${teachers[classnames[0]]}`,
        "entry.1556327835=出席",
        "entry.119822768=",
        `entry.634850437=${classnames[1]}`,
        `entry.714947543=${teachers[classnames[1]]}`,
        "entry.869445378=出席",
        "entry.1786512999=",
        `entry.403989627=${classnames[2]}`,
        `entry.604197935=${teachers[classnames[2]]}`,
        "entry.635206839=出席",
        "entry.17245382=",
        `entry.909035250=${classnames[3]}`,
        `entry.398244057=${teachers[classnames[3]]}`,
        "entry.2007587202=出席",
        "entry.904910944=",
        `entry.574229561=${classnames[4]}`,
        `entry.1113381671=${teachers[classnames[4]]}`,
        "entry.72674477=出席",
        "entry.405077547=",
        `entry.1739516506=${classnames[5]}`,
        `entry.871461081=${teachers[classnames[5]]}`,
        "entry.1308935777=出席",
        "entry.1174172028=",
        `entry.2061162996=${classnames[6]}`,
        `entry.1732679242=${teachers[classnames[6]]}`,
        "entry.1552416909=出席",
        "entry.257855159=",
        "entry.1235594214=無第八節",
        "entry.571339789=無第八節",
        "entry.85147417=無第八節",
        "entry.1296767361=",
    ]

    if (document.getElementById("go").checked) {
        var newUrl = submitUrl
    } else if (document.getElementById("wait").checked) {
        var newUrl = viewUrl
    }
    entrydata.forEach((item) => {
        newUrl += `${item}&`
    })

    window.open(newUrl)
}
