var data = [
    null,
    [
        "",
        [
            [1357037952, "填寫者姓名", null, 0, [[1856443187, null, 1]]],
            [
                1605712897,
                "班級",
                null,
                3,
                [
                    [
                        762925573,
                        [
                            ["301", null, null, null, 0],
                            ["302", null, null, null, 0],
                            ["303", null, null, null, 0],
                            ["304", null, null, null, 0],
                            ["305", null, null, null, 0],
                            ["306", null, null, null, 0],
                            ["307", null, null, null, 0],
                            ["308", null, null, null, 0],
                            ["309", null, null, null, 0],
                            ["310", null, null, null, 0],
                            ["311", null, null, null, 0],
                            ["312", null, null, null, 0],
                            ["313", null, null, null, 0],
                            ["314", null, null, null, 0],
                            ["315", null, null, null, 0],
                            ["316", null, null, null, 0],
                            ["317", null, null, null, 0],
                            ["318", null, null, null, 0],
                            ["319", null, null, null, 0],
                            ["320", null, null, null, 0],
                            ["321", null, null, null, 0],
                            ["322", null, null, null, 0],
                            ["323", null, null, null, 0],
                            ["324", null, null, null, 0],
                            ["325", null, null, null, 0],
                            ["326", null, null, null, 0],
                            ["327", null, null, null, 0],
                            ["328", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                24572961,
                "1.上課日期",
                null,
                9,
                [[917412650, null, 1, null, null, null, null, [0, 1]]],
            ],
            [
                986663738,
                "2.第一節",
                null,
                3,
                [
                    [
                        14235153,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                829485021,
                "3.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[329893755, null, 1]],
            ],
            [
                2127098016,
                "4.教師出席狀況",
                null,
                2,
                [
                    [
                        1556327835,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於4-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於4-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與4-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1938885379,
                "4-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[119822768, null, 0]],
            ],
            [
                1134695637,
                "5.上課章節/內容摘要（簡述）",
                null,
                1,
                [[1973655584, null, 1]],
            ],
            [
                360302987,
                "6.第二節",
                null,
                3,
                [
                    [
                        634850437,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                609733592,
                "7.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[714947543, null, 1]],
            ],
            [
                840872135,
                "8.教師出席狀況",
                null,
                2,
                [
                    [
                        869445378,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於8-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於8-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與8-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1941868436,
                "8-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[1786512999, null, 0]],
            ],
            [
                857385433,
                "9. 上課章節/內容摘要（簡述）",
                null,
                1,
                [[1806173177, null, 1]],
            ],
            [
                1044978206,
                "10.第三節",
                null,
                3,
                [
                    [
                        403989627,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                2062693589,
                "11.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[604197935, null, 1]],
            ],
            [
                686714720,
                "12.教師出席狀況",
                null,
                2,
                [
                    [
                        635206839,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於12-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於12-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與12-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1949153266,
                "12-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[17245382, null, 0]],
            ],
            [
                1103803254,
                "13.上課章節/內容摘要（簡述）",
                null,
                1,
                [[1292785364, null, 1]],
            ],
            [
                2093674265,
                "14.第四節",
                null,
                3,
                [
                    [
                        909035250,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                750400321,
                "15.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[398244057, null, 1]],
            ],
            [
                923196471,
                "16.教師出席狀況",
                null,
                2,
                [
                    [
                        2007587202,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於16-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於16-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與16-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                291518000,
                "16-1本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[904910944, null, 0]],
            ],
            [
                856964026,
                "17.上課章節/內容摘要（簡述）",
                null,
                1,
                [[1889140116, null, 0]],
            ],
            [
                1160010877,
                "18.第五節",
                null,
                3,
                [
                    [
                        574229561,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                801075953,
                "19.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[1113381671, null, 1]],
            ],
            [
                608575934,
                "20.教師出席狀況",
                null,
                2,
                [
                    [
                        72674477,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於20-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於20-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與20-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1812740227,
                "20-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[405077547, null, 0]],
            ],
            [
                446181537,
                "21.上課章節/內容摘要（簡述）",
                null,
                1,
                [[1602777528, null, 1]],
            ],
            [
                1032913993,
                "22.第六節",
                null,
                3,
                [
                    [
                        1739516506,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                790049442,
                "23.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[871461081, null, 1]],
            ],
            [
                756649130,
                "24.教師出席狀況",
                null,
                2,
                [
                    [
                        1308935777,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於24-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於24-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與24-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                290347248,
                "24-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[1174172028, null, 0]],
            ],
            [
                1330888413,
                "25. 上課章節/內容摘要（簡述）",
                null,
                1,
                [[1185553404, null, 1]],
            ],
            [
                1009480341,
                "26.第七節",
                null,
                3,
                [
                    [
                        2061162996,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1287140018,
                "27.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[1732679242, null, 1]],
            ],
            [
                1238097733,
                "28.教師出席狀況",
                null,
                2,
                [
                    [
                        1552416909,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於28-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於28-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與28-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                2266271,
                "28-1本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[257855159, null, 0]],
            ],
            [
                825065310,
                "29. 上課章節/內容摘要（簡述）",
                null,
                1,
                [[803151641, null, 1]],
            ],
            [
                196678485,
                "30.第八節",
                null,
                3,
                [
                    [
                        1235594214,
                        [
                            ["無第八節", null, null, null, 0],
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學（輔）", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["彈性學習－數學", null, null, null, 0],
                            ["公民", null, null, null, 0],
                            ["彈性學習－公民", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["彈性學習－地理", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["彈性學習－歷史", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物（輔）", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["彈性學習－生物", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理（輔）", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["彈性學習－物理", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學（輔）", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["彈性學習－化學", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["科技應用專題", null, null, null, 0],
                            ["邏輯辨證（一）", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["跨班加深加廣", null, null, null, 0],
                            ["跨班多元選修", null, null, null, 0],
                            ["自習", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1958263994,
                "31.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可；若無第八節的班級，填「無第八節」即可）",
                null,
                0,
                [[571339789, null, 1]],
            ],
            [
                959195205,
                "32.教師出席狀況",
                null,
                2,
                [
                    [
                        85147417,
                        [
                            ["無第八節", null, null, null, 0],
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於32-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於32-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與32-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                640017267,
                "32-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[1296767361, null, 0]],
            ],
            [
                1640686788,
                "33. 上課章節/內容摘要（簡述；若無第八節，請填「無第八節」即可）",
                null,
                1,
                [[221421666, null, 1]],
            ],
        ],
        ["", 1, 0, 1, 0],
        null,
        null,
        [1, 1],
        null,
        [1, ""],
        "110-1高三課程教室日誌        ",
        51,
        [null, null, null, 2, 0],
        null,
        null,
        null,
        null,
        [2],
        [[1, 1, 1, 1, 1], 1],
    ],
    "/forms",
    "110-1高三課程教室日誌2021.09.23更新",
    null,
    null,
    null,
    "1",
    null,
    0,
    1,
    null,
    "臺北市立建國高級中學",
    1,
    "e/1FAIpQLSdXlbwviHhDTCnzXxBWlN73SAEU7HaFVlvStOU0FaxUkCymUg",
    0,
    '[{"data":{"value":[]},"keyPath":["syncMap","applicationFonts","6"],"state":{"hashValue":"00000000"}},{"data":{"value":[]},"keyPath":["syncMap","domainFonts","0"],"state":{"hashValue":"00000000"}},{"data":{"familyList":["Alegreya","Amatic SC","Bree Serif","Calibri","Cambria","Merriweather","Permanent Marker","Pinyon Script","Playfair Display","Proxima Nova","Roboto","Roboto Mono","Ultra","Varela Round"],"recentlyUsedFamilyList":["LiHei Pro","Courier New","BiauKai","Arial","Times New Roman"],"transitionedFamilyList":[],"hasTransitioned":true},"keyPath":["syncMap","preferences","docs-fonts"],"state":{"timestamp":1622034479085335}},{"data":{"editorAnalyticsOnboarding":true,"blameLaunch":true,"saveIndicator":true,"smartCompose":true,"meetInEditorsPromo":true},"keyPath":["syncMap","preferences","docs-global_promos","0"],"state":{"timestamp":1628155928800995}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-unsupported_feature_warning_callout_bubble_shown_count"],"state":{"timestamp":1633014475350000}},{"data":{"value":false},"keyPath":["syncMap","preferences","mae-show_addons_menu_promo"],"state":{"timestamp":1633014475352000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-aips"],"state":{"timestamp":1633014475355000}},{"data":{},"keyPath":["syncMap","preferences","docs-homescreen-asp","6"],"state":{"timestamp":1628155928800995}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-homescreen-ftbdct"],"state":{"timestamp":1633014475355000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-dbs"],"state":{"timestamp":1633014475355000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-ht"],"state":{"timestamp":1633014475355000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-wws"],"state":{"timestamp":1633014475355000}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-etg-lvt"],"state":{"timestamp":1633014475357000}},{"data":{"value":true},"keyPath":["syncMap","preferences","docs-screenreader"],"state":{"timestamp":1629435255205059}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-enable_braille"],"state":{"timestamp":1629435255205059}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-mute_collaborators"],"state":{"timestamp":1629435255205059}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_chooser"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_link_form_promo"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_whats_new"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-expand_dasher_options"],"state":{"timestamp":1631668543776424}},{"data":{"proto":"[]"},"keyPath":["syncMap","preferences","freebird-auto_create_sink"],"state":{"timestamp":1633014475366000}},{"data":{"proto":"[]"},"keyPath":["syncMap","preferences","freebird-ui_version"],"state":{"timestamp":1633014475367000}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-questions_required_by_default"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-collect_usernames_by_default"],"state":{"timestamp":1631668543776424}},{"data":{"value":0},"keyPath":["syncMap","preferences","freebird-default_point_value"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_assessments_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-autovalidate_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_qxq_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_braveheart_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_manual_grading_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_record_view_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_brain_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-has_seen_braveheart_theme_warning"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_custom_themes_toast"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_edu_bundle_18_toast"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_quizzes_intro"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_question_import_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_locked_mode_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_draft_responses_modal"],"state":{"timestamp":1631668543776424}}]',
    1,
    0,
]

const subset = data[1][1]
let entrycode = []

subset.forEach((item) => {
    const entry = item[4][0][0]
    const title = item[1]
    entrycode.push(`entry.${entry}={${title}}`)
})

console.log(entrycode)
