var data = [
    null,
    [
        "學藝股長,您好:\n1.請每天確實填寫教室日誌，教學組將不定時抽查填寫情形，未依規定完成者登記愛校服務。\n2.請自111年2月11日(五)下午1時的課程開始填寫。\n3.若上課逾15分鐘老師尚未進教室，請學藝股長立刻至教務處通報。\n4.請逐日逐節一一填寫，一天若有７節課程，就要提交７次！敬請配合，非常感謝，謝謝。",
        [
            [1953857508, "填寫者姓名", null, 0, [[314173678, null, 1]]],
            [1324256958, "填寫者座號", null, 0, [[1738547215, null, 1]]],
            [
                463071139,
                "填寫者班級",
                null,
                3,
                [
                    [
                        1319745875,
                        [
                            ["301", null, null, null, 0],
                            ["302", null, null, null, 0],
                            ["303", null, null, null, 0],
                            ["304", null, null, null, 0],
                            ["305", null, null, null, 0],
                            ["306", null, null, null, 0],
                            ["307", null, null, null, 0],
                            ["308", null, null, null, 0],
                            ["309", null, null, null, 0],
                            ["310", null, null, null, 0],
                            ["311", null, null, null, 0],
                            ["312", null, null, null, 0],
                            ["313", null, null, null, 0],
                            ["314", null, null, null, 0],
                            ["315", null, null, null, 0],
                            ["316", null, null, null, 0],
                            ["317", null, null, null, 0],
                            ["318", null, null, null, 0],
                            ["319", null, null, null, 0],
                            ["320", null, null, null, 0],
                            ["321", null, null, null, 0],
                            ["322", null, null, null, 0],
                            ["323", null, null, null, 0],
                            ["324", null, null, null, 0],
                            ["325", null, null, null, 0],
                            ["326", null, null, null, 0],
                            ["327", null, null, null, 0],
                            ["328", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1985600533,
                "1.上課日期",
                null,
                9,
                [[1977272282, null, 1, null, null, null, null, [0, 1]]],
            ],
            [
                357801394,
                "2.節次",
                null,
                3,
                [
                    [
                        708837080,
                        [
                            ["1", null, null, null, 0],
                            ["2", null, null, null, 0],
                            ["3", null, null, null, 0],
                            ["4", null, null, null, 0],
                            ["5", null, null, null, 0],
                            ["6", null, null, null, 0],
                            ["7", null, null, null, 0],
                            ["8", null, null, null, 0],
                            ["9", null, null, null, 0],
                            ["10", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [2025761891, "3.課程科目", null, 0, [[331125135, null, 1]]],
            [
                1234203603,
                "4.上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[768699754, null, 1]],
            ],
            [
                202342877,
                "5.教師出席狀況",
                null,
                2,
                [
                    [
                        1276469790,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於5-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於5-1)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，與5-1皆免填",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1725751895,
                "5-1.本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)",
                null,
                1,
                [[1590862017, null, 0]],
            ],
            [
                1841287195,
                "6.上課章節/內容摘要（簡述）",
                null,
                1,
                [[1004856781, null, 1]],
            ],
            [
                155207748,
                "7.班上同學出席總人數(社課寫無)",
                null,
                0,
                [[1524799949, null, 1]],
            ],
            [2108176743, "8.備註", null, 1, [[1535546751, null, 0]]],
        ],
        ["", 1, 0, 1, 0],
        null,
        [
            null,
            null,
            null,
            null,
            null,
            [
                null,
                null,
                null,
                [255, 87, 34, null, 2],
                [255, 230, 222, null, 1],
            ],
        ],
        [1, 1],
        null,
        [1, ""],
        "110-2 高三課程教室日誌",
        52,
        [null, 0, null, 2, 0],
        null,
        null,
        null,
        null,
        [2],
        [[1, 1, 1, 1, 1], 1, 0, 2],
    ],
    "/forms",
    "110-2 高三課程教室日誌",
    null,
    null,
    null,
    "1",
    null,
    0,
    1,
    null,
    "臺北市立建國高級中學",
    1,
    "e/1FAIpQLSchHsm62uUM-UZd3Z5wIDZ8Hnzi6W8rsTQGgxBy04QIUbb6ag",
    0,
    '[{"data":{"value":[]},"keyPath":["syncMap","applicationFonts","6"],"state":{"hashValue":"00000000"}},{"data":{"value":[]},"keyPath":["syncMap","domainFonts","0"],"state":{"hashValue":"00000000"}},{"data":{"familyList":["Alegreya","Amatic SC","Bree Serif","Calibri","Cambria","Merriweather","Permanent Marker","Pinyon Script","Playfair Display","Proxima Nova","Roboto","Roboto Mono","Ultra","Varela Round"],"recentlyUsedFamilyList":["LiHei Pro","Courier New","BiauKai","Arial","Times New Roman"],"transitionedFamilyList":[],"hasTransitioned":true},"keyPath":["syncMap","preferences","docs-fonts"],"state":{"timestamp":1622034479085335}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-unsupported_feature_warning_callout_bubble_shown_count"],"state":{"timestamp":1644652987285000}},{"data":{"value":false},"keyPath":["syncMap","preferences","mae-show_addons_menu_promo"],"state":{"timestamp":1644652987288000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-aips"],"state":{"timestamp":1644652987290000}},{"data":{},"keyPath":["syncMap","preferences","docs-homescreen-asp","6"],"state":{"timestamp":1628155928800995}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-homescreen-ftbdct"],"state":{"timestamp":1644652987290000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-dbs"],"state":{"timestamp":1644652987290000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-ht"],"state":{"timestamp":1644652987290000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-wws"],"state":{"timestamp":1644652987290000}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-etg-lvt"],"state":{"timestamp":1644652987295000}},{"data":{"value":true},"keyPath":["syncMap","preferences","docs-screenreader"],"state":{"timestamp":1629435255205059}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-enable_braille"],"state":{"timestamp":1629435255205059}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-mute_collaborators"],"state":{"timestamp":1629435255205059}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_chooser"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_link_form_promo"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_whats_new"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-expand_dasher_options"],"state":{"timestamp":1631668543776424}},{"data":{"proto":"[]"},"keyPath":["syncMap","preferences","freebird-auto_create_sink"],"state":{"timestamp":1644652987304000}},{"data":{"proto":"[]"},"keyPath":["syncMap","preferences","freebird-ui_version"],"state":{"timestamp":1644652987306000}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-questions_required_by_default"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-collect_usernames_by_default"],"state":{"timestamp":1631668543776424}},{"data":{"value":0},"keyPath":["syncMap","preferences","freebird-default_point_value"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_assessments_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-autovalidate_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_qxq_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_braveheart_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_manual_grading_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_record_view_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_brain_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-has_seen_braveheart_theme_warning"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_custom_themes_toast"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_edu_bundle_18_toast"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_quizzes_intro"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_question_import_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_locked_mode_guided_help"],"state":{"timestamp":1631668543776424}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_draft_responses_modal"],"state":{"timestamp":1631668543776424}}]',
    1,
    0,
]

const subset = data[1][1]
let entrycode = []

subset.forEach((item) => {
    const entry = item[4][0][0]
    const title = item[1]
    entrycode.push(`entry.${entry}={${title}}`)
})

console.log(entrycode)
