var data = [
    null,
    [
        "學藝股長，您好:\n一、請每天確實填寫教室日誌，教學組於每週五結束後下週一查核，未依規定完成者登記愛校服務一次，二週未依規定完成者登記警告一次，請特別注意。\n二、本表請自111年3月01日(二)課程開始填寫。\n三、若上課逾15分鐘老師尚未進教室，請學藝股長立刻至教務處通報。\n四、一天提交一次，填寫時，上課日期請注意點選，謝謝。\n五、3/18第一定期考；5/02第二次定期考；4/28-29分科測驗第2次模擬考，定期考與模擬考當日不用填寫。",
        [
            [1953857508, "填寫者姓名", null, 0, [[314173678, null, 1]]],
            [1324256958, "填寫者座號", null, 0, [[1738547215, null, 1]]],
            [
                1815953083,
                "填寫者班級",
                null,
                3,
                [
                    [
                        359440102,
                        [
                            ["301", null, null, null, 0],
                            ["302", null, null, null, 0],
                            ["303", null, null, null, 0],
                            ["304", null, null, null, 0],
                            ["305", null, null, null, 0],
                            ["306", null, null, null, 0],
                            ["307", null, null, null, 0],
                            ["308", null, null, null, 0],
                            ["309", null, null, null, 0],
                            ["310", null, null, null, 0],
                            ["311", null, null, null, 0],
                            ["312", null, null, null, 0],
                            ["313", null, null, null, 0],
                            ["314", null, null, null, 0],
                            ["315", null, null, null, 0],
                            ["316", null, null, null, 0],
                            ["317", null, null, null, 0],
                            ["318", null, null, null, 0],
                            ["319", null, null, null, 0],
                            ["320", null, null, null, 0],
                            ["321", null, null, null, 0],
                            ["322", null, null, null, 0],
                            ["323", null, null, null, 0],
                            ["324", null, null, null, 0],
                            ["325", null, null, null, 0],
                            ["326", null, null, null, 0],
                            ["327", null, null, null, 0],
                            ["328", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1985600533,
                "上課日期",
                null,
                9,
                [[1977272282, null, 1, null, null, null, null, [0, 1]]],
            ],
            [756831993, "1-1 第一節課", null, 6],
            [
                1238021965,
                "1-2 課程科目",
                null,
                3,
                [
                    [
                        1949216775,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學輔", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["推理與證明(二)", null, null, null, 0],
                            ["數學專論", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理輔", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學輔", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物輔", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["地球科學", null, null, null, 0],
                            ["科學探究(地科)", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["公民與社會", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["資訊輔", null, null, null, 0],
                            ["資訊科技專題", null, null, null, 0],
                            ["機器人專題", null, null, null, 0],
                            ["資訊科技概論", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["運動學概論", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["創新生活與家庭", null, null, null, 0],
                            ["運動傷害與防護", null, null, null, 0],
                            ["專題寫作與表達", null, null, null, 0],
                            ["自然科學探究與實作A", null, null, null, 0],
                            ["自然科學探究與實作B", null, null, null, 0],
                            ["銜接課程", null, null, null, 0],
                            ["彈性學習", null, null, null, 0],
                            ["自主學習", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["自習", null, null, null, 0],
                            ["專題研究", null, null, null, 0],
                            ["獨立研究", null, null, null, 0],
                            ["高三多元選修", null, null, null, 0],
                            ["\u0002高三加深加廣1", null, null, null, 0],
                            ["高三加深加廣2", null, null, null, 0],
                            ["高三加深加廣3", null, null, null, 0],
                            ["高三加深加廣4", null, null, null, 0],
                            ["高三加深加廣5", null, null, null, 0],
                            ["高三加深加廣6", null, null, null, 0],
                            ["高三加深加廣7", null, null, null, 0],
                            ["高三加深加廣8", null, null, null, 0],
                            ["高三加深加廣9", null, null, null, 0],
                            ["高三加深加廣10", null, null, null, 0],
                            ["高三加深加廣11", null, null, null, 0],
                            ["歷史(彈性學習)", null, null, null, 0],
                            ["地理(彈性學習)", null, null, null, 0],
                            ["公民與社會(彈性學習)", null, null, null, 0],
                            ["數學(彈性學習)", null, null, null, 0],
                            ["物理(彈性學習)", null, null, null, 0],
                            ["化學(彈性學習)", null, null, null, 0],
                            ["生物(彈性學習)", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1234203603,
                "1-3 上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[768699754, null, 1]],
            ],
            [
                202342877,
                "1-4 教師出席狀況",
                null,
                2,
                [
                    [
                        1276469790,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於1-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於1-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，1-5填寫無",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1725751895,
                "1-5 本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)(若無者，請填「無」)",
                null,
                1,
                [[1590862017, null, 1]],
            ],
            [
                1841287195,
                "1-6 上課章節/內容摘要（簡述）",
                null,
                1,
                [[1004856781, null, 1]],
            ],
            [
                155207748,
                "1-7 班上同學出席總人數(社課請填「無」)",
                null,
                0,
                [[1524799949, null, 1]],
            ],
            [1189415199, "2-1 第二節課", null, 6],
            [
                1049473358,
                "2-2 課程科目",
                null,
                3,
                [
                    [
                        139315947,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學輔", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["推理與證明(二)", null, null, null, 0],
                            ["數學專論", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理輔", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學輔", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物輔", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["地球科學", null, null, null, 0],
                            ["科學探究(地科)", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["公民與社會", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["資訊輔", null, null, null, 0],
                            ["資訊科技專題", null, null, null, 0],
                            ["機器人專題", null, null, null, 0],
                            ["資訊科技概論", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["運動學概論", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["創新生活與家庭", null, null, null, 0],
                            ["運動傷害與防護", null, null, null, 0],
                            ["專題寫作與表達", null, null, null, 0],
                            ["自然科學探究與實作A", null, null, null, 0],
                            ["自然科學探究與實作B", null, null, null, 0],
                            ["銜接課程", null, null, null, 0],
                            ["彈性學習", null, null, null, 0],
                            ["自主學習", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["自習", null, null, null, 0],
                            ["專題研究", null, null, null, 0],
                            ["獨立研究", null, null, null, 0],
                            ["高三多元選修", null, null, null, 0],
                            ["\u0002高三加深加廣1", null, null, null, 0],
                            ["高三加深加廣2", null, null, null, 0],
                            ["高三加深加廣3", null, null, null, 0],
                            ["高三加深加廣4", null, null, null, 0],
                            ["高三加深加廣5", null, null, null, 0],
                            ["高三加深加廣6", null, null, null, 0],
                            ["高三加深加廣7", null, null, null, 0],
                            ["高三加深加廣8", null, null, null, 0],
                            ["高三加深加廣9", null, null, null, 0],
                            ["高三加深加廣10", null, null, null, 0],
                            ["高三加深加廣11", null, null, null, 0],
                            ["歷史(彈性學習)", null, null, null, 0],
                            ["地理(彈性學習)", null, null, null, 0],
                            ["公民與社會(彈性學習)", null, null, null, 0],
                            ["數學(彈性學習)", null, null, null, 0],
                            ["物理(彈性學習)", null, null, null, 0],
                            ["化學(彈性學習)", null, null, null, 0],
                            ["生物(彈性學習)", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1525333962,
                "2-3 上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[189849530, null, 1]],
            ],
            [
                414069238,
                "2-4 教師出席狀況",
                null,
                2,
                [
                    [
                        652051161,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於2-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於2-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，2-5填寫無",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                351795176,
                "2-5 本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)(若無者，請填「無」)",
                null,
                1,
                [[1847222004, null, 1]],
            ],
            [
                256689471,
                "2-6 上課章節/內容摘要（簡述）",
                null,
                1,
                [[367258215, null, 1]],
            ],
            [
                1502165549,
                "2-7 班上同學出席總人數(社課請填「無」)",
                null,
                0,
                [[1608389851, null, 1]],
            ],
            [1921591740, "3-1 第三節課", null, 6],
            [
                1354387626,
                "3-2 課程科目",
                null,
                3,
                [
                    [
                        994173459,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學輔", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["推理與證明(二)", null, null, null, 0],
                            ["數學專論", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理輔", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學輔", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物輔", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["地球科學", null, null, null, 0],
                            ["科學探究(地科)", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["公民與社會", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["資訊輔", null, null, null, 0],
                            ["資訊科技專題", null, null, null, 0],
                            ["機器人專題", null, null, null, 0],
                            ["資訊科技概論", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["運動學概論", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["創新生活與家庭", null, null, null, 0],
                            ["運動傷害與防護", null, null, null, 0],
                            ["專題寫作與表達", null, null, null, 0],
                            ["自然科學探究與實作A", null, null, null, 0],
                            ["自然科學探究與實作B", null, null, null, 0],
                            ["銜接課程", null, null, null, 0],
                            ["彈性學習", null, null, null, 0],
                            ["自主學習", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["自習", null, null, null, 0],
                            ["專題研究", null, null, null, 0],
                            ["獨立研究", null, null, null, 0],
                            ["高三多元選修", null, null, null, 0],
                            ["\u0002高三加深加廣1", null, null, null, 0],
                            ["高三加深加廣2", null, null, null, 0],
                            ["高三加深加廣3", null, null, null, 0],
                            ["高三加深加廣4", null, null, null, 0],
                            ["高三加深加廣5", null, null, null, 0],
                            ["高三加深加廣6", null, null, null, 0],
                            ["高三加深加廣7", null, null, null, 0],
                            ["高三加深加廣8", null, null, null, 0],
                            ["高三加深加廣9", null, null, null, 0],
                            ["高三加深加廣10", null, null, null, 0],
                            ["高三加深加廣11", null, null, null, 0],
                            ["歷史(彈性學習)", null, null, null, 0],
                            ["地理(彈性學習)", null, null, null, 0],
                            ["公民與社會(彈性學習)", null, null, null, 0],
                            ["數學(彈性學習)", null, null, null, 0],
                            ["物理(彈性學習)", null, null, null, 0],
                            ["化學(彈性學習)", null, null, null, 0],
                            ["生物(彈性學習)", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                33096314,
                "3-3 上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[908118448, null, 1]],
            ],
            [
                210685650,
                "3-4 教師出席狀況",
                null,
                2,
                [
                    [
                        874861447,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於3-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於3-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，3-5填寫無",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                2128779985,
                "3-5 本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)(若無者，請填「無」)",
                null,
                1,
                [[1769445044, null, 1]],
            ],
            [
                2105424730,
                "3-6 上課章節/內容摘要（簡述）",
                null,
                1,
                [[1207328731, null, 1]],
            ],
            [
                1787000970,
                "3-7 班上同學出席總人數(社課請填「無」)",
                null,
                0,
                [[245640882, null, 1]],
            ],
            [2033274811, "4-1 第四節課", null, 6],
            [
                1036503072,
                "4-2 課程科目",
                null,
                3,
                [
                    [
                        1804650846,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學輔", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["推理與證明(二)", null, null, null, 0],
                            ["數學專論", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理輔", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學輔", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物輔", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["地球科學", null, null, null, 0],
                            ["科學探究(地科)", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["公民與社會", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["資訊輔", null, null, null, 0],
                            ["資訊科技專題", null, null, null, 0],
                            ["機器人專題", null, null, null, 0],
                            ["資訊科技概論", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["運動學概論", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["創新生活與家庭", null, null, null, 0],
                            ["運動傷害與防護", null, null, null, 0],
                            ["專題寫作與表達", null, null, null, 0],
                            ["自然科學探究與實作A", null, null, null, 0],
                            ["自然科學探究與實作B", null, null, null, 0],
                            ["銜接課程", null, null, null, 0],
                            ["彈性學習", null, null, null, 0],
                            ["自主學習", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["自習", null, null, null, 0],
                            ["專題研究", null, null, null, 0],
                            ["獨立研究", null, null, null, 0],
                            ["高三多元選修", null, null, null, 0],
                            ["\u0002高三加深加廣1", null, null, null, 0],
                            ["高三加深加廣2", null, null, null, 0],
                            ["高三加深加廣3", null, null, null, 0],
                            ["高三加深加廣4", null, null, null, 0],
                            ["高三加深加廣5", null, null, null, 0],
                            ["高三加深加廣6", null, null, null, 0],
                            ["高三加深加廣7", null, null, null, 0],
                            ["高三加深加廣8", null, null, null, 0],
                            ["高三加深加廣9", null, null, null, 0],
                            ["高三加深加廣10", null, null, null, 0],
                            ["高三加深加廣11", null, null, null, 0],
                            ["歷史(彈性學習)", null, null, null, 0],
                            ["地理(彈性學習)", null, null, null, 0],
                            ["公民與社會(彈性學習)", null, null, null, 0],
                            ["數學(彈性學習)", null, null, null, 0],
                            ["物理(彈性學習)", null, null, null, 0],
                            ["化學(彈性學習)", null, null, null, 0],
                            ["生物(彈性學習)", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                195207757,
                "4-3 上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[987227560, null, 1]],
            ],
            [
                1526283735,
                "4-4 教師出席狀況",
                null,
                2,
                [
                    [
                        400122441,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於4-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於4-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，4-5填寫無",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1229193586,
                "4-5 本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)(若無者，請填「無」)",
                null,
                1,
                [[461480914, null, 1]],
            ],
            [
                1757530642,
                "4-6 上課章節/內容摘要（簡述）",
                null,
                1,
                [[130885767, null, 1]],
            ],
            [
                619896139,
                "4-7 班上同學出席總人數(社課請填「無」)",
                null,
                0,
                [[1418072502, null, 1]],
            ],
            [1031148933, "中午12:00-13:00午休", null, 8],
            [913715107, "5-1 第五節課", null, 6],
            [
                1390164722,
                "5-2 課程科目",
                null,
                3,
                [
                    [
                        742711143,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學輔", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["推理與證明(二)", null, null, null, 0],
                            ["數學專論", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理輔", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學輔", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物輔", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["地球科學", null, null, null, 0],
                            ["科學探究(地科)", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["公民與社會", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["資訊輔", null, null, null, 0],
                            ["資訊科技專題", null, null, null, 0],
                            ["機器人專題", null, null, null, 0],
                            ["資訊科技概論", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["運動學概論", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["創新生活與家庭", null, null, null, 0],
                            ["運動傷害與防護", null, null, null, 0],
                            ["專題寫作與表達", null, null, null, 0],
                            ["自然科學探究與實作A", null, null, null, 0],
                            ["自然科學探究與實作B", null, null, null, 0],
                            ["銜接課程", null, null, null, 0],
                            ["彈性學習", null, null, null, 0],
                            ["自主學習", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["自習", null, null, null, 0],
                            ["專題研究", null, null, null, 0],
                            ["獨立研究", null, null, null, 0],
                            ["高三多元選修", null, null, null, 0],
                            ["\u0002高三加深加廣1", null, null, null, 0],
                            ["高三加深加廣2", null, null, null, 0],
                            ["高三加深加廣3", null, null, null, 0],
                            ["高三加深加廣4", null, null, null, 0],
                            ["高三加深加廣5", null, null, null, 0],
                            ["高三加深加廣6", null, null, null, 0],
                            ["高三加深加廣7", null, null, null, 0],
                            ["高三加深加廣8", null, null, null, 0],
                            ["高三加深加廣9", null, null, null, 0],
                            ["高三加深加廣10", null, null, null, 0],
                            ["高三加深加廣11", null, null, null, 0],
                            ["歷史(彈性學習)", null, null, null, 0],
                            ["地理(彈性學習)", null, null, null, 0],
                            ["公民與社會(彈性學習)", null, null, null, 0],
                            ["數學(彈性學習)", null, null, null, 0],
                            ["物理(彈性學習)", null, null, null, 0],
                            ["化學(彈性學習)", null, null, null, 0],
                            ["生物(彈性學習)", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                459934497,
                "5-3 上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[843764124, null, 1]],
            ],
            [
                2013877340,
                "5-4 教師出席狀況",
                null,
                2,
                [
                    [
                        1608612244,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於5-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於5-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，5-5填寫無",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1504881010,
                "5-5 本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)(若無者，請填「無」)",
                null,
                1,
                [[494143557, null, 1]],
            ],
            [
                1437678314,
                "5-6 上課章節/內容摘要（簡述）",
                null,
                1,
                [[1124923929, null, 1]],
            ],
            [
                1734182112,
                "5-7 班上同學出席總人數(社課請填「無」)",
                null,
                0,
                [[812434060, null, 1]],
            ],
            [1335343881, "6-1 第六節課", null, 6],
            [
                1753365739,
                "6-2 課程科目",
                null,
                3,
                [
                    [
                        1431763546,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學輔", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["推理與證明(二)", null, null, null, 0],
                            ["數學專論", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理輔", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學輔", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物輔", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["地球科學", null, null, null, 0],
                            ["科學探究(地科)", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["公民與社會", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["資訊輔", null, null, null, 0],
                            ["資訊科技專題", null, null, null, 0],
                            ["機器人專題", null, null, null, 0],
                            ["資訊科技概論", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["運動學概論", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["創新生活與家庭", null, null, null, 0],
                            ["運動傷害與防護", null, null, null, 0],
                            ["專題寫作與表達", null, null, null, 0],
                            ["自然科學探究與實作A", null, null, null, 0],
                            ["自然科學探究與實作B", null, null, null, 0],
                            ["銜接課程", null, null, null, 0],
                            ["彈性學習", null, null, null, 0],
                            ["自主學習", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["自習", null, null, null, 0],
                            ["專題研究", null, null, null, 0],
                            ["獨立研究", null, null, null, 0],
                            ["高三多元選修", null, null, null, 0],
                            ["\u0002高三加深加廣1", null, null, null, 0],
                            ["高三加深加廣2", null, null, null, 0],
                            ["高三加深加廣3", null, null, null, 0],
                            ["高三加深加廣4", null, null, null, 0],
                            ["高三加深加廣5", null, null, null, 0],
                            ["高三加深加廣6", null, null, null, 0],
                            ["高三加深加廣7", null, null, null, 0],
                            ["高三加深加廣8", null, null, null, 0],
                            ["高三加深加廣9", null, null, null, 0],
                            ["高三加深加廣10", null, null, null, 0],
                            ["高三加深加廣11", null, null, null, 0],
                            ["歷史(彈性學習)", null, null, null, 0],
                            ["地理(彈性學習)", null, null, null, 0],
                            ["公民與社會(彈性學習)", null, null, null, 0],
                            ["數學(彈性學習)", null, null, null, 0],
                            ["物理(彈性學習)", null, null, null, 0],
                            ["化學(彈性學習)", null, null, null, 0],
                            ["生物(彈性學習)", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1775052344,
                "6-3 上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[1147247805, null, 1]],
            ],
            [
                1549405064,
                "6-4 教師出席狀況",
                null,
                2,
                [
                    [
                        1228559939,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於6-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於6-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，6-5填寫無",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1759065030,
                "6-5 本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)(若無者，請填「無」)",
                null,
                1,
                [[1425887865, null, 1]],
            ],
            [
                383944071,
                "6-6 上課章節/內容摘要（簡述）",
                null,
                1,
                [[2087671547, null, 1]],
            ],
            [
                647249414,
                "6-7 班上同學出席總人數(社課請填「無」)",
                null,
                0,
                [[851106728, null, 1]],
            ],
            [240430470, "7-1 第七節課", null, 6],
            [
                382517,
                "7-2 課程科目",
                null,
                3,
                [
                    [
                        1602143887,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學輔", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["推理與證明(二)", null, null, null, 0],
                            ["數學專論", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理輔", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學輔", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物輔", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["地球科學", null, null, null, 0],
                            ["科學探究(地科)", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["公民與社會", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["資訊輔", null, null, null, 0],
                            ["資訊科技專題", null, null, null, 0],
                            ["機器人專題", null, null, null, 0],
                            ["資訊科技概論", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["運動學概論", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["創新生活與家庭", null, null, null, 0],
                            ["運動傷害與防護", null, null, null, 0],
                            ["專題寫作與表達", null, null, null, 0],
                            ["自然科學探究與實作A", null, null, null, 0],
                            ["自然科學探究與實作B", null, null, null, 0],
                            ["銜接課程", null, null, null, 0],
                            ["彈性學習", null, null, null, 0],
                            ["自主學習", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["自習", null, null, null, 0],
                            ["專題研究", null, null, null, 0],
                            ["獨立研究", null, null, null, 0],
                            ["高三多元選修", null, null, null, 0],
                            ["\u0002高三加深加廣1", null, null, null, 0],
                            ["高三加深加廣2", null, null, null, 0],
                            ["高三加深加廣3", null, null, null, 0],
                            ["高三加深加廣4", null, null, null, 0],
                            ["高三加深加廣5", null, null, null, 0],
                            ["高三加深加廣6", null, null, null, 0],
                            ["高三加深加廣7", null, null, null, 0],
                            ["高三加深加廣8", null, null, null, 0],
                            ["高三加深加廣9", null, null, null, 0],
                            ["高三加深加廣10", null, null, null, 0],
                            ["高三加深加廣11", null, null, null, 0],
                            ["歷史(彈性學習)", null, null, null, 0],
                            ["地理(彈性學習)", null, null, null, 0],
                            ["公民與社會(彈性學習)", null, null, null, 0],
                            ["數學(彈性學習)", null, null, null, 0],
                            ["物理(彈性學習)", null, null, null, 0],
                            ["化學(彈性學習)", null, null, null, 0],
                            ["生物(彈性學習)", null, null, null, 0],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1934470677,
                "7-3 上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[1982764825, null, 1]],
            ],
            [
                322413876,
                "7-4 教師出席狀況",
                null,
                2,
                [
                    [
                        1791598565,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於7-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於7-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，7-5填寫無",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        1,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                68216800,
                "7-5 本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)(若無者，請填「無」)",
                null,
                1,
                [[1417860346, null, 1]],
            ],
            [
                1807077179,
                "7-6 上課章節/內容摘要（簡述）",
                null,
                1,
                [[1181011054, null, 1]],
            ],
            [
                331277353,
                "7-7 班上同學出席總人數(社課請填「無」)",
                null,
                0,
                [[1947217148, null, 1]],
            ],
            [2119775099, "8-1 第八節課", null, 6],
            [
                1949638124,
                "8-2 課程科目",
                null,
                3,
                [
                    [
                        1999721695,
                        [
                            ["國文", null, null, null, 0],
                            ["英文", null, null, null, 0],
                            ["數學", null, null, null, 0],
                            ["數學輔", null, null, null, 0],
                            ["數學統整", null, null, null, 0],
                            ["推理與證明(二)", null, null, null, 0],
                            ["數學專論", null, null, null, 0],
                            ["物理", null, null, null, 0],
                            ["物理輔", null, null, null, 0],
                            ["物理統整", null, null, null, 0],
                            ["物理專論", null, null, null, 0],
                            ["物理進階探究", null, null, null, 0],
                            ["化學", null, null, null, 0],
                            ["化學輔", null, null, null, 0],
                            ["化學統整", null, null, null, 0],
                            ["化學專論", null, null, null, 0],
                            ["化學進階探究", null, null, null, 0],
                            ["生物", null, null, null, 0],
                            ["生物輔", null, null, null, 0],
                            ["生物統整", null, null, null, 0],
                            ["生物進階探究", null, null, null, 0],
                            ["地球科學", null, null, null, 0],
                            ["科學探究(地科)", null, null, null, 0],
                            ["歷史", null, null, null, 0],
                            ["地理", null, null, null, 0],
                            ["公民與社會", null, null, null, 0],
                            ["生涯規劃", null, null, null, 0],
                            ["生命教育", null, null, null, 0],
                            ["生活科技", null, null, null, 0],
                            ["家政", null, null, null, 0],
                            ["資訊科技", null, null, null, 0],
                            ["資訊輔", null, null, null, 0],
                            ["資訊科技專題", null, null, null, 0],
                            ["機器人專題", null, null, null, 0],
                            ["資訊科技概論", null, null, null, 0],
                            ["美術", null, null, null, 0],
                            ["藝術生活", null, null, null, 0],
                            ["音樂", null, null, null, 0],
                            ["體育", null, null, null, 0],
                            ["體育專項術科", null, null, null, 0],
                            ["運動學概論", null, null, null, 0],
                            ["全民國防教育", null, null, null, 0],
                            ["健康與護理", null, null, null, 0],
                            ["創新生活與家庭", null, null, null, 0],
                            ["運動傷害與防護", null, null, null, 0],
                            ["專題寫作與表達", null, null, null, 0],
                            ["自然科學探究與實作A", null, null, null, 0],
                            ["自然科學探究與實作B", null, null, null, 0],
                            ["銜接課程", null, null, null, 0],
                            ["彈性學習", null, null, null, 0],
                            ["自主學習", null, null, null, 0],
                            ["班會", null, null, null, 0],
                            ["綜合活動", null, null, null, 0],
                            ["自習", null, null, null, 0],
                            ["專題研究", null, null, null, 0],
                            ["獨立研究", null, null, null, 0],
                            ["高三多元選修", null, null, null, 0],
                            ["\u0002高三加深加廣1", null, null, null, 0],
                            ["高三加深加廣2", null, null, null, 0],
                            ["高三加深加廣3", null, null, null, 0],
                            ["高三加深加廣4", null, null, null, 0],
                            ["高三加深加廣5", null, null, null, 0],
                            ["高三加深加廣6", null, null, null, 0],
                            ["高三加深加廣7", null, null, null, 0],
                            ["高三加深加廣8", null, null, null, 0],
                            ["高三加深加廣9", null, null, null, 0],
                            ["高三加深加廣10", null, null, null, 0],
                            ["高三加深加廣11", null, null, null, 0],
                            ["歷史(彈性學習)", null, null, null, 0],
                            ["地理(彈性學習)", null, null, null, 0],
                            ["公民與社會(彈性學習)", null, null, null, 0],
                            ["數學(彈性學習)", null, null, null, 0],
                            ["物理(彈性學習)", null, null, null, 0],
                            ["化學(彈性學習)", null, null, null, 0],
                            ["生物(彈性學習)", null, null, null, 0],
                        ],
                        0,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                2014517800,
                "8-3 上課教師（跨班選修課程、綜合活動、自習課...等，若無固定任課老師，填「無」即可）",
                null,
                0,
                [[397311866, null, 0]],
            ],
            [
                1022743296,
                "8-4 教師出席狀況",
                null,
                2,
                [
                    [
                        1852365507,
                        [
                            ["出席", null, null, null, 0],
                            ["缺席(完全未到班上課)", null, null, null, 0],
                            [
                                "請假(代課教師姓名請填於8-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "調課(調課日期、節次、調課教師請填於8-5)",
                                null,
                                null,
                                null,
                                0,
                            ],
                            [
                                "跨班選修課程、自習、綜合活動...等，無固定教師的課程，8-5填寫無",
                                null,
                                null,
                                null,
                                0,
                            ],
                        ],
                        0,
                        null,
                        null,
                        null,
                        null,
                        null,
                        0,
                    ],
                ],
            ],
            [
                1326447034,
                "8-5 本節代課教師姓名(如為調課請填調課日期、節次、調課教師姓名)(若無者，請填「無」)",
                null,
                1,
                [[2097501323, null, 0]],
            ],
            [
                1735396925,
                "8-6 上課章節/內容摘要（簡述）",
                null,
                1,
                [[154306953, null, 0]],
            ],
            [
                2070646356,
                "8-7 班上同學出席總人數(社課請填「無」)",
                null,
                0,
                [[889417550, null, 0]],
            ],
            [1686211214, "今日填寫完畢，確認後提交，謝謝。", null, 6],
        ],
        ["", 1, 0, 1, 0],
        null,
        [
            null,
            null,
            null,
            null,
            null,
            [
                null,
                null,
                null,
                [255, 87, 34, null, 2],
                [255, 230, 222, null, 1],
            ],
        ],
        [1, 1],
        null,
        [1, ""],
        "110-2 高三課程教室日誌(1110301更新版)",
        52,
        [null, 0, null, 2, 0],
        null,
        null,
        null,
        null,
        [2],
        [[1, 1, 1, 1, 1], 1, 0, 2],
    ],
    "/forms",
    "110-2高三課程教室日誌 (1110301更新版) ",
    null,
    null,
    null,
    "1",
    null,
    0,
    1,
    null,
    "臺北市立建國高級中學",
    1,
    "e/1FAIpQLScLkLSE78Dftw8LV__5IGv47D_brhy5YlzJ8-p7M79FzKvCkA",
    0,
    '[{"data":{"value":[]},"keyPath":["syncMap","applicationFonts","6"],"state":{"hashValue":"00000000"}},{"data":{"value":[]},"keyPath":["syncMap","domainFonts","0"],"state":{"hashValue":"00000000"}},{"data":{"familyList":["Alegreya","Amatic SC","Bree Serif","Calibri","Cambria","Merriweather","Permanent Marker","Pinyon Script","Playfair Display","Proxima Nova","Roboto","Roboto Mono","Ultra","Varela Round"],"recentlyUsedFamilyList":["LiHei Pro","Courier New","BiauKai","Arial","Times New Roman"],"transitionedFamilyList":[],"hasTransitioned":true},"keyPath":["syncMap","preferences","docs-fonts"],"state":{"timestamp":1622034479085335}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-unsupported_feature_warning_callout_bubble_shown_count"],"state":{"timestamp":1647060917684000}},{"data":{"value":false},"keyPath":["syncMap","preferences","mae-show_addons_menu_promo"],"state":{"timestamp":1647060917685000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-aips"],"state":{"timestamp":1647060917686000}},{"data":{},"keyPath":["syncMap","preferences","docs-homescreen-asp","6"],"state":{"timestamp":1628155928800995}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-homescreen-ftbdct"],"state":{"timestamp":1647060917686000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-dbs"],"state":{"timestamp":1647060917686000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-ht"],"state":{"timestamp":1647060917686000}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-homescreen-wws"],"state":{"timestamp":1647060917686000}},{"data":{"value":0},"keyPath":["syncMap","preferences","docs-etg-lvt"],"state":{"timestamp":1647060917689000}},{"data":{"value":true},"keyPath":["syncMap","preferences","docs-screenreader"],"state":{"timestamp":1645861870537861}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-enable_braille"],"state":{"timestamp":1645861870537861}},{"data":{"value":false},"keyPath":["syncMap","preferences","docs-mute_collaborators"],"state":{"timestamp":1645861870537861}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_chooser"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_link_form_promo"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_whats_new"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-expand_dasher_options"],"state":{"timestamp":1644656482024355}},{"data":{"proto":"[]"},"keyPath":["syncMap","preferences","freebird-auto_create_sink"],"state":{"timestamp":1647060917695000}},{"data":{"proto":"[]"},"keyPath":["syncMap","preferences","freebird-ui_version"],"state":{"timestamp":1647060917697000}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-questions_required_by_default"],"state":{"timestamp":1644656482024355}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-collect_usernames_by_default"],"state":{"timestamp":1644656482024355}},{"data":{"value":0},"keyPath":["syncMap","preferences","freebird-default_point_value"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_assessments_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-autovalidate_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_qxq_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_braveheart_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_manual_grading_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_record_view_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_brain_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-has_seen_braveheart_theme_warning"],"state":{"timestamp":1644656482024355}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_custom_themes_toast"],"state":{"timestamp":1644656482024355}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_edu_bundle_18_toast"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_quizzes_intro"],"state":{"timestamp":1644656482024355}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_question_import_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-show_locked_mode_guided_help"],"state":{"timestamp":1644656482024355}},{"data":{"value":false},"keyPath":["syncMap","preferences","freebird-show_draft_responses_modal"],"state":{"timestamp":1644656482024355}},{"data":{"value":true},"keyPath":["syncMap","preferences","freebird-expanded_fonts_guided_help"],"state":{"timestamp":1644656482024355}}]',
    1,
    0,
]

const subset = data[1][1]
let entrycode = []

subset.forEach((item) => {
    try {
        const entry = item[4][0][0]
        const title = item[1]
        entrycode.push(`entry.${entry}={${title}}`)
    } catch (error) {}
})

console.log(entrycode)
